### ISSUE TITLE
Need to clarify a doubt... 

### ISSUE THREAD

**Issue by taradepan** [microsoft/SATechnicalOnboarding#26]
hi, I already have a portfolio that I created using Next Js. It's currently running on Vercel.  if I change from vercel to azure static apps, will it be considered as completed?

**Comment by tessawiedmann** [comment]
Hey @taradepan - you will have to complete all of the sections listed in the instructions for Technical Onboarding here, which includes more than just creating the portfolio website:
https://github.com/microsoft/SATechnicalOnboarding/blob/main/technical-onboarding-instructions.md

It's great that you already have a website, but the Portfolio website section also is important because it introduces you to tools like GitHub Codespaces and GitHub Copilot, so please follow the full Technical Onboarding instructions
